version: "3.1"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./toniData:/data/tonidb
    environment:
      - MONGO_INITDB_DATABASE= Toni
    ports:
      - 27017:27017