version: "3.1"

services:
  mongo:
    container_name: toni-app-mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./toniData:/data/tonidb
    environment:
      - MONGO_INITDB_DATABASE= Toni
    ports:
      - 27017:27017
  app:
    container_name: toni-app-express-server
    restart: always
    build: ./
    ports:
      - "9001:9001"
    links:
      - mongo
    env_file:
      - .env